[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mini-gen"
version = "0.0.0"
readme = "README.md"
requires-python = ">=3.11"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]

[tool.hatch.build.targets.wheel]
packages = ["src"]
