model:
  latent_dim: 100
  feature_maps: 64
  lr: 2.e-4
  beta1: 0.5

data:
  data_dir: "./data"
  batch_size: 128
  num_workers: 4

trainer:
  max_epochs: 20
  accelerator: "auto"
  devices: 1
  precision: 32
