model:
  timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02

data:
  data_dir: "./data"
  batch_size: 128
  num_workers: 4

trainer:
  max_epochs: 100
  accelerator: "auto"
  devices: 1
  precision: 32
